### ISSUE TITLE
Improve Fig7

### ISSUE THREAD

**Issue by JJ** [salem23/WCCI2018#8]
First, not clear what the units are in Axis Y. Damage and Maxspeed are measured in the same unit? Then, of course, sort.

**Comment by salem23** [comment]
Sorry @JJ  I haven't R installed to use ggplot
I uploaded the data in text and csv format
for the evolution of points,  I think  we have to choose between the evolution of points on every race or put the races results like Fig 6
I uploaded the data  for the evolution too
I will revise the references now  @amorag
